language: ruby
rvm:
  - 1.9.3
  - 2.0.0
install:
  - gem update --system
  - gem install bundler --pre
  - gem install tf -v '>=0.4.2'
  - gem install specific_install
  - gem specific_install -l https://github.com/infertux/bashcov.git
before_script:
  - gem install bundler --pre
  - rvm alias delete default
  - hash -r
  - ./install
  - rvm-smile
  - git submodule init
  - git submodule update
script: bashcov -- tf --text rvm-test/fast/* rvm-test-rvm1/*
after_script:
  - cat coverage/index.html
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
      - "irc.freenode.org#rvm"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
